repos:
  - repo: https://github.com/Takishima/cmake-pre-commit-hooks
    rev: v1.8.1
    hooks:
      - id: clang-format
        args:
          - '-i'
      - id: clang-tidy
        args:
          # TODO: Remove when upstream issue is fixed
          # https://gitlab.kitware.com/cmake/cmake/-/issues/24827
          # https://github.com/Takishima/cmake-pre-commit-hooks/issues/63
          - '-Bcmake-build-pre-commit'
          - '--preset'
          - 'pre-commit'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
        exclude: docs\/.*
  - repo: https://github.com/executablebooks/mdformat
    # TODO: Temporarily separate docs formatiing
    # https://github.com/executablebooks/mdformat/issues/234
    # TODO: Disabled due to lack of colon-fence support
    rev: 0.7.16
    hooks:
      - id: mdformat
        stages: [ manual ]
        additional_dependencies:
          - mdformat-myst
        files: doc\/(?!README).*\.md$
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.0
    hooks:
      - id: check-github-workflows
